module.exports = [
  // Electronics
  {
    name: 'MacBook Pro 14"',
    description: 'Apple M3 Pro chip, 18GB unified memory, 512GB SSD. The most powerful laptop for professionals with an incredible Liquid Retina XDR display.',
    price: 1999.99,
    image_url: 'https://picsum.photos/seed/macbook/400/400',
    category: 'Electronics',
    stock: 30,
    rating: 4.8,
    review_count: 3214,
  },
  {
    name: 'Samsung Galaxy S24 Ultra',
    description: '6.8-inch QHD+ Dynamic AMOLED, 200MP camera, built-in S Pen, 5000mAh battery. The ultimate Android flagship.',
    price: 1199.99,
    image_url: 'https://picsum.photos/seed/phone/400/400',
    category: 'Electronics',
    stock: 50,
    rating: 4.7,
    review_count: 2876,
  },
  {
    name: 'Sony WH-1000XM5 Headphones',
    description: 'Industry-leading noise cancelling with 30-hour battery life, multipoint connection, and exceptional sound quality.',
    price: 349.99,
    image_url: 'https://picsum.photos/seed/headphones/400/400',
    category: 'Electronics',
    stock: 80,
    rating: 4.9,
    review_count: 5432,
  },
  {
    name: 'Apple Watch Series 9',
    description: 'Advanced health sensors, always-on Retina display, 18-hour battery, Double Tap gesture. Carbon neutral.',
    price: 429.99,
    image_url: 'https://picsum.photos/seed/applewatch/400/400',
    category: 'Electronics',
    stock: 60,
    rating: 4.7,
    review_count: 1923,
  },
  {
    name: 'iPad Air 11"',
    description: 'M2 chip, 11-inch Liquid Retina display, 256GB, Wi-Fi 6E. Versatile powerhouse for creativity and productivity.',
    price: 749.99,
    image_url: 'https://picsum.photos/seed/ipad/400/400',
    category: 'Electronics',
    stock: 45,
    rating: 4.8,
    review_count: 1587,
  },
  {
    name: 'Mechanical Keyboard MK Pro',
    description: 'Tactile Cherry MX Brown switches, RGB backlit, aluminum frame, compact TKL layout. For developers and gamers.',
    price: 129.99,
    image_url: 'https://picsum.photos/seed/keyboard/400/400',
    category: 'Electronics',
    stock: 100,
    rating: 4.6,
    review_count: 3102,
  },

  // Books
  {
    name: 'Clean Code',
    description: 'A Handbook of Agile Software Craftsmanship by Robert C. Martin. Essential reading for every software developer who wants to write better code.',
    price: 34.99,
    image_url: 'https://picsum.photos/seed/cleancode/400/400',
    category: 'Books',
    stock: 200,
    rating: 4.7,
    review_count: 8901,
  },
  {
    name: 'Atomic Habits',
    description: 'An Easy & Proven Way to Build Good Habits & Break Bad Ones by James Clear. The #1 New York Times bestseller.',
    price: 18.99,
    image_url: 'https://picsum.photos/seed/atomichabits/400/400',
    category: 'Books',
    stock: 300,
    rating: 4.9,
    review_count: 12340,
  },
  {
    name: 'The Pragmatic Programmer',
    description: 'Your Journey to Mastery. 20th Anniversary Edition by David Thomas & Andrew Hunt. A must-read for modern developers.',
    price: 42.99,
    image_url: 'https://picsum.photos/seed/pragmatic/400/400',
    category: 'Books',
    stock: 150,
    rating: 4.8,
    review_count: 4521,
  },

  // Home & Kitchen
  {
    name: 'Ninja Air Fryer Pro',
    description: '5.5-quart capacity, 9-in-1 functionality, up to 75% less fat. Perfect for healthy, crispy meals in minutes.',
    price: 119.99,
    image_url: 'https://picsum.photos/seed/airfryer/400/400',
    category: 'Home & Kitchen',
    stock: 75,
    rating: 4.7,
    review_count: 6723,
  },
  {
    name: 'Nespresso Vertuo Next',
    description: 'Single-serve coffee and espresso machine, 5 cup sizes, auto-detects capsule, 54oz water tank. Barista-quality at home.',
    price: 179.99,
    image_url: 'https://picsum.photos/seed/nespresso/400/400',
    category: 'Home & Kitchen',
    stock: 60,
    rating: 4.6,
    review_count: 4312,
  },
  {
    name: 'Instant Pot Duo 7-in-1',
    description: '8-quart electric pressure cooker, slow cooker, rice cooker, steamer, sauté, yogurt maker, and warmer in one device.',
    price: 89.99,
    image_url: 'https://picsum.photos/seed/instantpot/400/400',
    category: 'Home & Kitchen',
    stock: 90,
    rating: 4.7,
    review_count: 9812,
  },

  // Sports & Outdoors
  {
    name: 'Lululemon Yoga Mat',
    description: '5mm thick, sweat-wicking natural rubber, alignment lines, slip-resistant surface. 71" x 26" for full range of motion.',
    price: 78.00,
    image_url: 'https://picsum.photos/seed/yogamat/400/400',
    category: 'Sports',
    stock: 120,
    rating: 4.8,
    review_count: 3450,
  },
  {
    name: 'Nike Air Zoom Pegasus 40',
    description: 'Versatile running shoe with React foam cushioning, Zoom Air unit, and breathable mesh upper. For everyday training.',
    price: 129.99,
    image_url: 'https://picsum.photos/seed/nikepegasus/400/400',
    category: 'Sports',
    stock: 80,
    rating: 4.6,
    review_count: 2134,
  },
  {
    name: 'Adjustable Dumbbell Set',
    description: 'Bowflex SelectTech 552, replaces 15 sets of weights, 5-52.5 lbs each, adjusts in 2.5 lb increments. Space-saving home gym.',
    price: 399.99,
    image_url: 'https://picsum.photos/seed/dumbbells/400/400',
    category: 'Sports',
    stock: 35,
    rating: 4.8,
    review_count: 5678,
  },

  // Fashion
  {
    name: 'Patagonia Nano Puff Jacket',
    description: 'Lightweight, packable insulation for three-season use. PrimaLoft® Gold Insulation, recycled shell fabric, water-resistant.',
    price: 229.00,
    image_url: 'https://picsum.photos/seed/jacket/400/400',
    category: 'Fashion',
    stock: 55,
    rating: 4.7,
    review_count: 1892,
  },
  {
    name: 'Levi\'s 501 Original Jeans',
    description: 'The original straight fit jeans that started it all. Button fly, 100% cotton denim, sits at waist, straight leg.',
    price: 69.50,
    image_url: 'https://picsum.photos/seed/levis/400/400',
    category: 'Fashion',
    stock: 150,
    rating: 4.5,
    review_count: 7823,
  },
  {
    name: 'New Balance 574 Sneakers',
    description: 'Classic heritage running-inspired sneaker. Suede and mesh upper, ENCAP midsole technology, rubber outsole.',
    price: 89.99,
    image_url: 'https://picsum.photos/seed/newbalance/400/400',
    category: 'Fashion',
    stock: 100,
    rating: 4.6,
    review_count: 4321,
  },
];
